<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<a href="#header" class="backtop show-on-desktops">返回顶部 ^</a>
	<div id="footer" class="container">
		<footer class="row"> <section
			class="three columns show-on-desktops">
		<h5>
			<strong>联系我们</strong>
		</h5>
		<p>
			本站所有影片资源均来自网络，如有侵犯您的权益，可发送邮件至：<a
				href="mailto:yuanlong1318@126.com">yuanlong1318#126.com</a> 或联系我的微博 <a href="http://weibo.com/528880906" target="_blank">@wyl_leon</a>
		</p>
		</section> <section class="five columns">
		<h5>
			<strong>关于MoiveRss/ <a href="/about">About us</a></strong>
		</h5>
		<p>
			MoiveRss（www.dyrss.com）是一个第一时间提供高清电影资源快播播放地址的平台。本站所有资源将通过网络渠道收录至本站并供网友查看，所有资源将保证90%为高清播放地址，如有发现非高清资源，请及时联系站长删除。<a
				href="/about">详细介绍 →</a>
		</p>
		</section> <section class="four columns show-on-desktops" style="color:gray">
		<h6>
			<strong></strong>
		</h6>
		<p>
			本站由<a target="_blank" href="http://http://code.google.com/appengine">Google App Engine<img src="/images/appengine_lowres.png" 
alt="Powered by Google App Engine" /> </a>
			提供服务器
		</p>
		<p style="text-align: right; float: right">
			
		</p>
		<p class="">&copy;2012-2013 MoiveRSS</p>
		<p></p>
		</section> </footer>
	</div>