<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<aside class="sidebarcol three282 columns sibarcol">
			<div class="featuredbox show-on-desktops panel">
				<p>
					<a href="http://www.dyrss.com">高清电影订阅中心</a>是一个第一时间获取网络高清电影资源的平台。
					本站所有资源将通过网络渠道收录至本站并供网友查看，所有资源将保证90%为高清播放地址，如有发现非高清资源，请及时联系站长删除。同时也希望您能提供第一手高清快播电影资源播放地址。
				</p>
			</div>
			<div class="boxs show-on-desktops">
				<dl class="tabs">
					<dd>
						<a href="#oday_crop" class="active">站长邮箱</a>
					</dd>
				</dl>
				<ul class="tabs-content">
					<li id="oday_cropTab" class="active" style="display: block;"><div
							class="alert-box">
							wyl_leon<a class="url"
								href="mailto:yuanlong1318@126.com?subject=[高清电影订阅]">yuanlong1318@126.com</a>
						</div></li>
				</ul>
			</div>
			<div class="boxs show-on-desktops">
				<dl class="tabs">
					<dd>
						<a href="#oday_weibo" class="active">站长微博</a>
					</dd>
				</dl>
				<ul class="tabs-content">
					<li id="oday_weiboTab" class="active" style="display: block;">
						<iframe width="100%" height="<%=wb_h%>" class="share_self"
							frameborder="0" scrolling="no"
							src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=<%=wb_h%>&fansRow=2&ptype=1&speed=0&skin=5&isTitle=1&noborder=1&isWeibo=1&isFans=1&uid=1395451254&verifier=28da7c8b&dpc=1"></iframe>
					</li>
				</ul>
			</div>
			</aside>