<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>	<div class="w960 marM">
		<div class="home-foot">
			<table class="box-shadow-corner-home">
	               <tr class="bs-header">
	                   <td class="bs-left"></td>
	                   <td class="bs-middle"></td>
	                   <td class="bs-right"></td>
	               </tr>
	               <tr class="bs-body">
	                   <td class="bs-left"></td>
	                   <td class="bs-main">
							<div class="clearfix">
								<dl>
									<dt>关于我们</dt>
									<dd>
										<a href="/about" target="_blank">
										关于我们
										</a>
									</dd>
									<dd>
										<a href="/" target="_blank">
										QQ:757577749
										</a>
									</dd>
									<dd>
										<a href="/" target="_blank">
										Email:yuanlong1318#126.com
										</a>
									</dd>
								</dl>
								<dl>
									<dt>特别声明</dt>
									<dd><a>本站所有影片资源均来自网络 </a></dd>
									<dd><a>如有侵犯您的权益，可发送邮件</a></dd>
									<dd><a>至：yuanlong1318#126.com</a></dd>
									<dd><a>或联系我的微博 </a><a target="_blank" href="http://weibo.com/528880906">@wyl_leon</a>
									</dd>
								</dl>
								<dl>
									<dt>友情链接</dt>
									<dd>
										<a href="http://www.jrj.com.cn" target="_blank">
										金融界
										</a>
									</dd>
									<dd>
										<a href="http://win.jrj.com.cn" target="_blank">
										第五届民间股市高手大赛
										</a>
									</dd>
									<dd>
										<a href="http://i.jrj.com.cn" target="_blank">
										金融界社区
										</a>
									</dd>
									<dd>
										<a href="http://weibo.com/528880906" target="_blank">
										申请友链
										</a>
									</dd>
								</dl>
								<dl>
									<dt>
										关注我们
									</dt>
									<dd>
										<a class="home-qzone">
										</a>
									</dd>
									<dd>
										<a class="home-sina">
										</a>
									</dd>
									<dd>
										<a id="J_homeFeedBack" href="http://weibo.com/528880906" target="_blank" class="home-feedback">
										意见反馈
										</a>
									</dd>
								</dl>
							</div>
							<p><a style="display: block;width: 36px;height: 36px;background: url('images/footer~1.png') -66px 0 no-repeat;" href="aboutl~1.htm" target="_blank"></a></p>
							<p class="copy-right" style="padding-top: 5px; ">Copyright &copy;2012-2013 MoiveRSS 免费高清电影订阅中心 </p>
					</td>
                   <td class="bs-right"></td>
               </tr>
               <tr class="bs-footer">
                   <td class="bs-left"></td>
                   <td class="bs-middle"></td>
                   <td class="bs-right"></td>
               </tr>
			</table>
		</div>
	</div>
<script type="text/javascript">
	 $(function(){
	 $("img").each(function(){
	 	$(this).bind("error",function(){
	 		$(this).attr("src","/v2/images/npic.jpg");
	 	})
	 });
	 });
	</script>