function guidGenerator(){var a=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}function cc6_readCookie(a){var c="";a+="=";if(document.cookie.length>0&&(offset=document.cookie.indexOf(a),offset!=-1)){offset+=a.length;end=document.cookie.indexOf(";",offset);if(end==-1)end=document.cookie.length;c=unescape(document.cookie.substring(offset,end))}return c}
function cc6_writeCookie(a,c,d){var b="";d!=null&&(b=new Date((new Date).getTime()+d*36E5),b="; expires="+b.toGMTString());document.cookie=a+"="+escape(c)+b+"; path=/"}function writeCookie(a,c,d){var b="";d!=null&&(b=new Date((new Date).getTime()+d*36E5),b="; expires="+b.toGMTString());document.cookie=a+"="+escape(c)+b}function getCookieValue(){var a=cc6_readCookie("k_meitu_uuid");a!=null&&a!=""||(a=guidGenerator(),cc6_writeCookie("k_meitu_uuid",a,87600));return a}
function showPrice(){$(".picture").hover(function(){$(this).css({border:"1px solid #fcb484"});$(".price",this).css({display:"block"})},function(){$(this).css({border:"1px solid #E7E6E6"});$(".price",this).css({display:"none"})})}function isIE6(){return document.all&&typeof document.body.style.maxHeight==="undefined"}
function sendAjaxForFavoShop(a,c){var d=cc6_readCookie("user_id");if(d!==null&&d!==""&&d!=='""')if(a!=""){var b=$("#"+a);b.attr("title")!=="\u53d1\u9001\u8bf7\u6c42\u4e2d..."&&(b.attr({title:"\u53d1\u9001\u8bf7\u6c42\u4e2d..."}),$.getJSON("./uploadCollectShops.do?shopId="+a+"&t="+Math.random()*10,function(a){a==0?(a="\u53d6\u6d88\u6536\u85cf",c==1&&(a="\u5df2\u6536\u85cf"),b.removeClass("shop-collect").addClass("shop-collect-unlike").html(a).attr({title:"\u4e0d\u559c\u6b22\u6211\u4e86\u5c31\u70b9\u51fb\u5427\uff5e"})):
(a==1?alert("\u6536\u85cf\u5931\u8d25\uff01"):a==2&&createLoginDialog(),b.attr({title:"\u559c\u6b22\u6211\u5c31\u70b9\u51fb\u6536\u85cf\u5427\uff01"}));b=null}))}else alert("\u6536\u85cf\u5931\u8d25\uff01");else createLoginDialog()}
function sendAjaxForCancelFavoShop(a){var c=cc6_readCookie("user_id");if(c!==null&&c!==""&&c!=='""')if(a!=""){var d=$("#"+a);d.attr("title")!=="\u53d1\u9001\u8bf7\u6c42\u4e2d..."&&(d.attr({title:"\u53d1\u9001\u8bf7\u6c42\u4e2d..."}),$.getJSON("./cancelCollectShops.do?shopId="+a+"&t="+Math.random()*10,function(a){a==0?d.removeClass("shop-collect-unlike").addClass("shop-collect").html(" \u6536\u3000\u85cf ").attr({title:"\u559c\u6b22\u5c31\u70b9\u51fb\u6211\u5427\uff01"}):(a==1?alert("\u53d6\u6d88\u6536\u85cf\u5931\u8d25\uff01"):
a==2&&createLoginDialog(),d.attr({title:"\u4e0d\u559c\u6b22\u6211\u4e86\u5c31\u70b9\u51fb\u5427\uff5e\uff01"}));d=null}))}else alert("\u53d6\u6d88\u6536\u85cf\u5931\u8d25\uff01");else createLoginDialog()}
function sendAjaxForFavo(a,c,d){var b=cc6_readCookie("user_id");if(b!==null&&b!==""&&b!=='""')if(a!=""){var e=$("#"+a);e.attr("title")!=="\u53d1\u9001\u8bf7\u6c42\u4e2d..."&&(e.attr({title:"\u53d1\u9001\u8bf7\u6c42\u4e2d..."}),b="./uploadFavoriteItems.do?itemId="+a+"&t="+Math.random()*10,c!==void 0&&(b+=c),$.getJSON(b,function(b){if(b==0){d!==1?(b=parseInt(e.text())+1,isNaN(b)&&(b="\u53d6\u6d88\u6536\u85cf")):(b=parseInt(e.find(".favo-amount-content").text())+1,b=isNaN(b)?" \u5df2\u6536\u85cf":' \u5df2\u6536\u85cf (<em class="favo-amount-content">'+
b+"</em>)");var c=e.children(".collect-tips");showCollectTips(c);setTimeout('hideCollectTips("#'+a+' .collect-tips")',900);e.removeClass("picture-favorites").addClass("picture-cancel-favo").attr({title:"\u4e0d\u559c\u6b22\u6211\u5c31\u70b9\u51fb\u53d6\u6d88\u6536\u85cf\uff01"}).children(".favorite-amount").html(b)}else b==1?alert("\u6536\u85cf\u5931\u8d25\uff01"):b==2&&createLoginDialog(),e.attr({title:"\u559c\u6b22\u6211\u5c31\u70b9\u51fb\u6536\u85cf\u5427\uff01"});e=null}))}else alert("\u6536\u85cf\u5931\u8d25\uff01");
else createLoginDialog()}
function sendAjaxForCancelFavo(a,c,d){var b=cc6_readCookie("user_id");if(b!==null&&b!==""&&b!=='""')if(a!=""){var e=$("#"+a);e.attr("title")!=="\u53d1\u9001\u8bf7\u6c42\u4e2d..."&&(e.attr({title:"\u53d1\u9001\u8bf7\u6c42\u4e2d..."}),b="./cancelFavoriteItems.do?itemId="+a+"&t="+Math.random()*10,c!==void 0&&(b+=c),$.getJSON(b,function(b){if(b==0){d!==1?(b=parseInt(e.text())-1,isNaN(b)?b="\u6536\u3000\u3000\u85cf":b<0&&(b=0)):(b=parseInt(e.find(".favo-amount-content").text())-1,isNaN(b)?b=" \u6536\u3000\u85cf":
(b<0&&(b=0),b=' \u6536\u3000\u85cf (<em class="favo-amount-content">'+b+"</em>)"));var c=e.children(".collect-tips");showCollectTips(c);setTimeout('hideCollectTips("#'+a+' .collect-tips")',900);e.removeClass("picture-cancel-favo").addClass("picture-favorites").attr({title:"\u559c\u6b22\u6211\u5c31\u70b9\u51fb\u6536\u85cf\u5427\uff01"}).children(".favorite-amount").html(b)}else b==1?alert("\u53d6\u6d88\u6536\u85cf\u5931\u8d25\uff01"):b==2&&createLoginDialog(),e.attr({title:"\u4e0d\u559c\u6b22\u6211\u5c31\u70b9\u51fb\u53d6\u6d88\u6536\u85cf\uff01"});
e=null}))}else alert("\u53d6\u6d88\u6536\u85cf\u5931\u8d25\uff01");else createLoginDialog()}function showCollectTips(a){a.css({display:"block"});a.children(".tips-round-2").show(100);a.children(".tips-round-action").show(300)}
function hideCollectTips(a){var a=$(a),c=a.children(".tips-round-action");a.hide(300,function(){c.is(".tips-add-bg")?c.removeClass("tips-add-bg").addClass("tips-delete-bg").html('<img class="png" alt="\u6536\u85cf-1" src="../images/tips_delete_one.png"/>'):c.removeClass("tips-delete-bg").addClass("tips-add-bg").html('<img class="png" alt="\u6536\u85cf+1" src="../images/tips_add_one.png"/>')});c.hide(100);a.children(".tips-round-2").hide(100)}
function doPositionFixed(){$("#goTop").doPositionFixed({threshold:10,position:{bottom:10,right:60}}).click(function(){$("html, body").animate({scrollTop:0})})}var displayTD=0;
function searchWord(){var a=$("#J_searchList"),c=$("#J_searchAll"),d=$("#J_search");$("#J_searchWordCn").css("color",function(){if($(this).val()=="\u641c\u5b9d\u8d1d")return"#787878";if($(this).val()=="")return $(this).val("\u641c\u5b9d\u8d1d"),"#787878"}).focus(function(){var b=$(this).val();b!==""&&(b=="\u641c\u5b9d\u8d1d"?($(this).val("").css({color:"#666"}),d.removeClass("search-form-default").addClass("search-form-used")):a.css({display:"block"}));c.css({background:"#f2f2f2"});b=wordLimitLength($(this).val(),
5);wordKeep(b)}).blur(function(){displayTD==0&&($(this).val()==""&&($(this).val("\u641c\u5b9d\u8d1d").css({color:"#787878"}),d.removeClass("search-form-used").addClass("search-form-default")),c.css({background:"#f2f2f2"}),a.css({display:"none"}),wordKeep(""))})}
function searchCategoryHover(){var a=$("#J_searchList");$(".search-keyword").hover(function(){a.css({display:"block"});$(this).css({background:"#f2f2f2"});displayTD=1},function(){$(this).css({background:"#fff"});$(this).is("#J_searchAll")||a.css({display:"none"});displayTD=0})}
function searchEventListener(){var a=document.getElementById("J_searchWordCn"),c=$("#J_searchList"),d=$("#J_searchAll");a.addEventListener("input",function(){var b=a.value;b==""?c.css({display:"none"}):a.value!=="\u641c\u5b9d\u8d1d"&&(d.css({background:"#f2f2f2"}),c.css({display:"block"}),b=wordLimitLength(a.value,5));wordKeep(b)},!1)}
function wordKeep(a){document.getElementById("J_allkeyword").innerHTML=a;document.getElementById("J_girlkeyword").innerHTML=a;document.getElementById("J_boyskeyword").innerHTML=a;document.getElementById("J_ladyskeyword").innerHTML=a;document.getElementById("J_kidskeyword").innerHTML=a;document.getElementById("J_technologykeyword").innerHTML=a}function wordLimitLength(a,c){if(a.length>c)var d=a,b=d,a=b=d.substring(0,c-1)+"...";return a}
function URIEncodeSearch(){var a=$("#J_searchWordCn").attr("value"),a=encodeURIComponent(encodeURIComponent(a));$("#J_searchWord").attr("value",a)}function searchEnterPress(a){if(a=a?a:window.event?window.event:"")if(keyCode=a.keyCode?a.keyCode:a.which?a.which:a.charCode,keyCode==13)return URIEncodeSearch(),$("#J_searchForm").submit(),!1}
function doSubmitForm(a){var c=$("#J_searchWordCn").val();if(c==="\u641c\u5b9d\u8d1d"||c==="")return preventFormSubmit(a),alert("\u8bf7\u586b\u5199\u5b9d\u8d1d\u540d\uff01"),!1;a=encodeURIComponent(encodeURIComponent(c));$("#J_searchWord").attr("value",a);return!0}function preventFormSubmit(a){if(a=a?a:window.event?window.event:"")a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a.returnValue=!1,a.cancelBubble=!0)}
function imgsLoadError(a){a.bind("error",function(){var a=this.src,d=this,b=$(this).parent(),e=b.siblings(".picture-loading");this.src="images/default2.png";$(this).attr("original")===void 0&&this.setAttribute("original",a);var i=$(".picture_reload",$(this).parents(".picture-picture"));b.css({"background-color":"#fff8f8"});i.css({display:"block"});e.css({display:"none"});i.unbind("click");i.click(function(){var a=$(this).siblings(".picture-wrapper").find("img");b.css({"background-color":"#fff"});
i.css({display:"none"});e.css({display:"block"});$(d).bind("load",function(){e.css({display:"none"});$(d).unbind("load")});a[0].src=a[0].getAttribute("original");a=null;return!1})})}
function loadImages(a){for(var c=a.length,d=0;d<c;d++)(function(a,c){var d=new Image,j=$(a).parent();d.id=c;var h=j.siblings(".picture-loading"),g=$(".picture_reload",$(a).parents(".picture-picture"));if(g.size()<1){var f=[];f.push('<p class="picture_reload">');f.push('<a href="#"');f.push(">\u91cd\u65b0\u52a0\u8f7d</a></p>");f=f.join("");g=$(f)}g.unbind("click");g.click(function(){var a=$(this).siblings(".picture-wrapper").find("img");h.fadeIn();a[0].src=a[0].getAttribute("original");loadImages(a);
return!1});d.onload=function(){var c=[];c.width=d.width;c.height=d.height;$(a).css(c);g.css({display:"none"});h.css({display:"none"});g=j=h=null;d=d.onload=null};d.onerror=function(){var b;var c=a.src;a.src="images/default2.png";$(a).attr("original")===void 0&&a.setAttribute("original",c);j.css({"background-color":"#fff8f8"});h.css({display:"none"});b=j=d.onerror=null,d=b};d.src=a.src})(a[d],d)}
function resizeImagesPosition(a,c){for(var d=a.length,b=0;b<d;b++)(function(a){var b=new Image,d=$(a).parent();b.onload=function(){var h=[];h.width=b.width;h.height=b.height;h.height>c.height&&$.extend(h,{top:-(h.height-c.height)/2,left:0,position:"absolute"});h.width>c.width?$.extend(h,{top:0,left:-(h.width-c.width)/2,position:"absolute"}):h.width<c.width&&$.extend(h,{top:0,left:-(h.width-c.width)/2,position:"absolute"});$(a).css(h);d.siblings(".picture-loading").css({display:"none"});d=null;b=b.onload=
null};b.onerror=function(){var c=a.src;a.src="images/default_item.png";$(a).attr("original")===void 0&&a.setAttribute("original",c);d.css({"background-color":"#fff8f8"});d.siblings(".picture-loading").css({display:"none"});d=null;b=b.onerror=null};b.src=a.src})(a[b],b)}
function imagesForShow(a,c){for(var d=a.length,b=0;b<d;b++)(function(a,b){var d=new Image,h=$(a).parent().siblings(".picture-loading"),g=$(".picture_reload",$(a).parents(".picture-picture"));if(g.size()<1){var f=[];f.push('<p class="picture_reload">');f.push('<a href="#"');f.push(">\u91cd\u65b0\u52a0\u8f7d</a></p>");f=f.join("");g=$(f)}g.unbind("click");g.click(function(){var a=$(this).siblings(".picture-wrapper").find("img");h.fadeIn();a[0].src=a[0].getAttribute("original");imagesForShow(a,c);return!1});
d.onload=function(){var b=imageResize(d.width,d.height,c.width,c.height);$(a).css({width:b.width,height:b.height});$(a).parent().css({"background-color":"#ffffff"});g.hide();h.fadeOut("fast");g=imgParent=null;d=d.onload=null};d.onerror=function(){var c=a.src;a.src="images/default2.png";$(a).attr("original")===void 0&&a.setAttribute("original",c);(c=a.getAttribute("data-original-index"))?b=c:(a.setAttribute("data-original-index",b),$(a).parents(".picture-picture").append(g));$(a).parent().css({"background-color":"#fff8f8"});
h.fadeOut("fast");imgParent=null;d=d.onerror=null};d.src=a.src})(a[b],b)}
function resetImage(a,c,d){for(var b=a.length,e=0;e<b;e++)(function(a){var b=new Image,e=$(a).parent().siblings(".picture-loading"),g=$(".picture_reload",$(a).parent().parent());if(g.size()<1){var f=[];f.push('<p class="picture_reload" style="">');f.push('<a href="#"');f.push(">\u91cd\u65b0\u52a0\u8f7d</a></p>");f=f.join("");g=$(f);g.css({width:c.width});c.width<110&&(g.addClass("picture_reload_min"),c.width<61&&g.css({bottom:-5}));$(a).parent().parent().append(g)}g.unbind("click");g.click(function(){var a=
$(this).siblings("a").find("img");e.fadeIn();a[0].src=a[0].getAttribute("original");resetImage(a,c);return!1});b.onload=function(){if(d){var f=imageResizeWithMeansZoom(b.width,b.height,c.width,c.height);f.height>c.height&&$(a).css({top:-(f.height-c.height)/2,left:0,position:"absolute"});f.width>c.width&&$(a).css({top:0,left:-(f.width-c.width)/2,position:"absolute"})}else f=imageResizeWithTwoLimit(b.width,b.height,c.width,c.height);$(a).css({width:f.width,height:f.height});$(a).parent().css({"background-color":"#ffffff"});
g.hide();e.css({display:"none"});e=g=null;b=b.onload=null};b.onerror=function(){var c=a.src;a.src="images/default2.png";$(a).attr("original")===void 0&&a.setAttribute("original",c);$(a).parent().css({"background-color":"#fff8f8"});e.fadeOut("fast");b=b.onerror=null};b.src=a.src})(a[e],e)}function imageResizeWithMeansZoom(a,c,d,b){var e={};e.width=a;e.height=c;a/c>=d/b?(e.width=b*a/c,e.height=b):(e.width=d,e.height=d*c/a);return e}
function imageResizeWithTwoLimit(a,c,d,b){var e={};e.width=a;e.height=c;if(a>d)e.width=d,e.height=d*c/a;if(e.height>b)e.width=b*a/c,e.height=b;return e}function imageResize(a,c,d){var b={};a>d?(b.width=d,b.height=Math.ceil(d*c/a)):(b.width=a,b.height=c);return b}
function AddFavorite(a,c){try{window.external.addFavorite(a,c)}catch(d){try{window.sidebar.addPanel(c,a,"")}catch(b){alert("\u4f60\u7684\u6d4f\u89c8\u5668\u6682\u4e0d\u652f\u6301\u76f4\u63a5\u6536\u85cf\uff0c\u70e6\u8bf7\u4f7f\u7528Ctrl+D\u6536\u85cf\u672c\u9875\u9762\uff01")}}};
